# Generated by Django 5.1.4 on 2024-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='Автор отсутствует', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, default='Ссылка отсутствует', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
