# Generated by Django 5.1.4 on 2024-12-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_subject_subtopic_journalarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
