# Generated by Django 5.1.4 on 2024-12-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_sciencefield_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaluzNauki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва галузі науки')),
            ],
            options={
                'verbose_name': 'Галузь науки',
                'verbose_name_plural': 'Галузі науки',
            },
        ),
        migrations.CreateModel(
            name='Vidannya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Назва видання')),
                ('galuz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vidannya', to='knowledge.galuznauki', verbose_name='Галузь науки')),
            ],
            options={
                'verbose_name': 'Видання',
                'verbose_name_plural': 'Видання',
            },
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='ScienceField',
        ),
    ]
